(inmueble (direccion "C/Calas, 9") (zona madrid) (precio 2000) (metros-cuadrados 250) (n-habitaciones 4) (accesible no) (garaje si) (transaccion alquiler))
(inmueble (direccion "C/Pensamiento, 13, 3ºE") (zona madrid) (precio 150000) (metros-cuadrados 110) (n-habitaciones 3) (accesible si) (garaje si) (transaccion compra))
(inmueble (direccion "C/Verdadera, 1, 3ºE") (zona madrid) (precio 150000) (metros-cuadrados 110) (n-habitaciones 3) (accesible si) (garaje no) (transaccion compra))
(inmueble (direccion "C/Turing, 123, 3ºE") (zona madrid) (precio 150000) (metros-cuadrados 100) (n-habitaciones 4) (accesible si) (garaje no) (transaccion compra))
(inmueble (direccion "C/Godel, 123, 3ºE") (zona madrid) (precio 140000) (metros-cuadrados 110) (n-habitaciones 4) (accesible si) (garaje no) (transaccion compra))
(inmueble (direccion "C/Landauer, 0.0172 eV") (zona madrid) (precio 140000) (metros-cuadrados 110) (n-habitaciones 5) (accesible si) (garaje no) (transaccion compra))
(inmueble (direccion "C/Menor, 1, 1A") (zona madrid) (precio 1) (metros-cuadrados 499) (n-habitaciones 9) (accesible no) (garaje si) (transaccion alquiler))
